import sqlite3
import unicodedata

#ouvre le classeur
conn = sqlite3.connect('./instance/pharmaapp.sqlite')

#sert d'intermediaire à la db pour insérer, supprimer etc, exec des commandes à la db
c = conn.cursor()

medicaments = [
    ('Abacavir','Ziagen®'),
    ('Abacavir/Lamivudine','Kivexa®'),
    ('Abacavir/Lamivudine/Zidovudine','Trizivir®'),
    ('Abiratérone Acétate','Zytiga®'),
    ('Acamprosate','Aotal®'),
    ('Acarbose','Glucor®'),
    ('Acébutolol','Sectral®'),
    ('Azélastine Chlorhydrate propionate','Dymista®'),
    ('Acéclofénac','Cartrex®'),
    ('Acétylcystéine','Fluimucil® Expectorant®'),
    ('Acétylleucine','TanganilPRO®'),
    ('Aciclovir','Zovirax®'),
    ('Acide alendronique','Fosamax®'),
    ('Acide alendronique/Vitamine D3 ', 'Fosavance®'),
    ('Acide folique', 'Spéciafoldine®'),
    ('Acide fusidique', 'Fucidine®'),
    ('Acide gadotérique', 'Dotarem®'),
    ('Acide tiaprofénique', 'Surgam®'),
    ('Acide tranexamique', 'Exacyl®'),
    ('Acide ursodésoxycholique', 'Delursan®'),
    ('Acide zolédronique1', 'Aclasta®'),
    ('Acide zolédronique2', 'Zometa®'),
    ('Adapalène', 'Différine®'),
    ('Adrénaline', 'Epipen®'),
    ('Agomélatine', 'Valdoxan®'),
    ('Alfuzosine', 'Xatral®'),
    ('Alginate de sodium/Bicarbonate de sodium', 'Gaviscon®'),
    ('Alitrétinoïne', 'Toctino®'),
    ('Allopurinol', 'Zyloric®'),
    ('Almotriptan', 'Almogran®'),
    ('Alprazolam', 'Xanax®'),
    ('Alvérine/Siméticone', 'Meteospasmyl®'),
    ('Ambroxol', 'Ambroxol®'),
    ('Amifampridine','Firdapse®'),
    ('Amiloride/Hydrochlorothiazide','Modurétic®'),
    ('Amiodarone','Cordarone®'),
    ('Amisulpride','Solian®'),
    ('Amlodipine','Amlor®'),
    ('Amlodipine/Valsartan','Exforge®'),
    ('Amorolfine','Loceryl®'),
    ('Amoxicilline','Clamoxyl®'),
    ('Amoxicilline/Acide clavulanique','Augmentin®'),
    ('Amylmétacrésol/Alcool dichlorobenzylique','Strepsils Miel Citron®'),
    ('Amylmétacrésol/Alcool dichlorobenzylique/Lidocaïne','Strepsils Lidocaïne®'),
    ('Anagrélide','Xagrid®'),
    ('Anastrozole','Arimidex®'),
    ('Apomorphine','Apokinon®'),
    ('Aprépitant','Emend®'),
    ('Aripiprazole','Abilify®'),
    ('Atazanavir','Reyataz®'),
    ('Aténolol', 'Tenormine®'),
    ('Aténolol/Nifedipine', 'Tenordate®'),
    ('Atorvastatine','Tahor®'),
    ('Atovaquone','Wellvone®'),
    ('Atovaquone/Proguanil','Malarone®'),
    ('Azathioprine','Imurel®'),
    ('Azithromycine', 'Zithromax®'),
    ('Antalnox', 'Apranax®'),
    ('Baclofène', 'Liorésal®'),
    ('Béclométasone', 'Beclospin®'),
    ('Bénazépril', 'Cibacène®'),
    ('Bénazépril/Hydrochlorothiazide', 'Cibadrex®'),
    ('Bétahistine', 'Bétaserc®'),
    ('Bétaméthasone', 'Célestène®'),
    ('Bétaxolol', 'Kerlone®'),
    ('Bexarotène', 'Targretin®'),
    ('Bicalutamide', 'Casodex®'),
    ('Bilastine', 'Bilaska®'),
    ('Bimatoprost', 'Lumigan®'),
    ('Bimatoprost/Timolol', 'Ganfort®'),
    ('Bisacodyl1', 'Contalax™'),
    ('Bisacodyl2', 'Dulcolax®'),
    ('Bisoprolol', 'Cardensiel® - Detensiel® si >= 10mg'),
    ('Bisoprolol/Hydrochlorothiazide', 'Lodoz®'),
    ('Borax/Acide borique', 'Dacryoserum®'),
    ('Brimonidine', 'Alphagan®'),
    ('Brimonidine/Timolol', 'Combigan®'),
    ('Brinzolamide', 'Azopt®'),
    ('Brinzolamide/Timolol', 'Azarga®'),
    ('Bromazépam', 'Lexomil®'),
    ('Budésonide1', 'Pulmicort®'),
    ('Budésonide2', 'Rhinocort®'),
    ('Buprénorphine', 'Subutex®'),
    ('Buprénorphine/Naloxone', 'Suboxone®'),
    ('Buspirone', 'Buspar®'),
    ('Cabergoline', 'Dostinex®'),
    ('Calcifédiol', 'Dédrogyl®'),
    ('Calcipotriol/Bétaméthasone', 'Daivobet®'),
    ('Calcitonine', 'Miacalcic®'),
    ('Candésartan', 'Atacand®'),
    ('Candésartan/Hydrochlorothiazide', 'Hytacand®'),
    ('Capécitabine', 'Xeloda®'),
    ('Captopril', 'Lopril®'),
    ('Captopril/Hydrochlorothiazide', 'Captea (Arrêt commercialisation) - Ecazide® (Arrêt commercialisation)'),
    ('Carbamazépine', 'Tégrétol®'),
    ('Carbidopa/Lévodopa', 'Sinemet®'),
    ('Carbocistéine', 'Mucoplexil®'),
    ('Carbomère 940', 'Aquarest®'),
    ('Carvédilol', 'Kredex®'),
    ('Céfépime', 'Axepim®'),
    ('Céfixime', 'Oroken®'),
    ('Cefpodoxime', 'Orelox®'),
    ('Ceftazidime', 'Fortum®'),
    ('Ceftriaxone', 'Rocéphine®'),
    ('Céfuroxime', 'Zinnat®'),
    ('Célécoxib', 'Celebrex®'),
    ('Céliprolol','Célectol®'),
    ('Cétirizine', 'Zyrtec®'),
    ('Chlorhexidine/Benzalkonium/ Alcool benzylique', 'Biseptine®'),
    ('Chlorhexidine/Chlorobutanol','Eludrilpro®'),
    ('Chlorhydrate d"oxycodone/ Chlorhydrate de naloxone','Oxsynia®'),
    ('Chlormadinone','Lutéran®'),
    ('Cholecalciferol','Uvédose®'),
    ('Ciclétanine','Tenstaten®'),
    ('Ciclopirox','Mycoster® 8%'),
    ('Ciclopirox Olamine1','Mycoster® 1%'),
    ('Ciclopirox Olamine2','Sebiprox®'),
    ('Cinacalcet','Mimpara®'),
    ('Ciprofibrate','Lipanor®'),
    ('Ciprofloxacine','Ciflox®'),
    ('Citalopram','Seropram®'),
    ('Clarithromycine','Zeclar®'),
    ('Clobétasol','Clobex®- Dermoval® Clarelux'),
    ('Clomipramine','Anafranil®'),
    ('Clopidogrel acide acetylsallycilique','DuoPlavin®'),
    ('Clopidogrel', 'Plavix®'),
    ('Clotrimazole', 'MycoHydralin®'),
    ('Cloxacilline', 'Orbénine®'),
    ('Clozapine', 'Leponex®'),
    ('Cotrimoxazole', 'Bactrim® Forte'),
    ('Cromoglicate de sodium', 'Opticron®'),
    ('Cyamémazine', 'Tercian®'),
    ('Cyprotérone', 'Androcur®'),
    ('Cyprotérone/Ethinylestradiol (2 mg/0,035 mg)', 'Diane® 35 µg'),
    ('Cystine/Vitamine B6', 'Cystine B6 Bailleul®'),
    ('Cimetidine', 'Tagamet®'),
    ('Darunavir', 'Prezista®'),
    ('Dasatinib', 'Sprycel®'),
    ('Déférasirox', 'Exjade®'),
    ('Desloratadine', 'Aerius®'),
    ('Désogestrel 75 µg', 'Cérazette®'),
    ('Désogestrel/Ethinylestradiol (150 µg/20 µg) et (150 µg/30 µg)', 'Désobel®'),
    ('Désogestrel/Ethinylestradiol (150 µg/20 µg)', 'Mercilon®'),
    ('Désogestrel/Ethinylestradiol (150 µg/30 µg) 21 cp', 'Varnoline®'),
    ('Désogestrel/Ethinylestradiol (150 µg/30 µg) 28 cp', 'Varnoline® continu'),
    ('Dexpanthenol', 'Bepanthen®'),
    ('Dextromethorphane', 'Tussidane®'),
    ('Diacéréine', 'Art® - Zondar®'),
    ('Diazépam', 'Valium®'),
    ('Diclofenac', 'Voltarène®'),
    ('Dabigatran', 'Pradaxa®'),
    ('Diénogest', 'Visanne®'),
    ('Diltiazem', 'Tildiem®'),
    ('Diméthyl Fumarate', 'Tecfidera®'),
    ('Diosmectite','Smecta®'),
    ('Diosmine','Diovenor®'),
    ('Divalproate de sodium','Depakote®'),
    ('Domperidone','Motilium®'),
    ('Donépézil','Aricept®'),
    ('Dorzolamide','Trusopt®'),
    ('Dorzolamide/Timolol','Cosopt®'),
    ('Doxazosine','Zoxan®'),
    ('Doxycycline','Doxy®'),
    ('Doxylamine','Donormyl®'),
    ('Duloxétine','Cymbalta®'),
    ('Dutastéride','Avodart®'),
    ('Dutastéride/Tamsulosine','Combodart®'),
    ('Etifoxine','Stresam®'),
    ('Ébastine','Kestin®'),
    ('Éconazole','Gyno-Pevaryl®'),
    ('Éfavirenz/Emtricitabine/Tenofovir disoproxyl','Atripla'),
    ('Élétriptan','Relpax®'),
    ('Emtricitabine/Tenofovir disoproxil','Truvada®'),
    ('Enalapril','Renitec®'),
    ('Enalapril/Hydrochlorothiazide','Co-Renitec®'),
    ('Enalapril/Lercanidipine','Lercapress®'),
    ('Entacapone','Comtan®'),
    ('Entécavir','Baraclude®'),
    ('Éplérénone','Inspra®'),
    ('Erlotinib','Tarceva®'),
    ('Erythromycine','Ery®'),
    ('Escitalopram','Séroplex®'),
    ('Ésoméprazole','Inexium®'),
    ('Ethinylestradiol/Drospirénone (0,02 mg/3 mg continu) 21 cp + 7 cp 4 G','Jasminellecontinu®'),
    ('Ethinylestradiol/Drospirénone (0.02 mg/3 mg continu) 24 cp + 4cp','Yaz®'),
    ('Ethinylestradiol/Drospirénone (0,02 mg/3 mg) 4G','Jasminelle®'),
    ('Ethinylestradiol/Drospirenone (0,02 mg/3 mg) et (0,03 mg/3 mg) 4G','Drospibel®'),
    ('Ethinylestradiol/Drospirenone (0.03 mg/3 mg) 4G','Jasmine®'),
    ('Ethinylestradiol/Etonogestrel','Nuvaring®'),
    ('Ethinylestradiol/Etonogestrel 15 microgrammes/ 120 microgrammes/24 heures','Etoring®'),
    ('Etoricoxib','Arcoxia®'),
    ('Éverolimus','Afinitor®'),
    ('Éxemestane','Aromasine®'),
    ('Ézétimibe','Ezetrol®'),
    ('Ézétimibe/Simvastatine','Inegy®'),
    ('Ézétimibe/Atorvastatine','Liptruzet®'),
    ('Énoxaparine','Lovenox®'),
    ('Fébuxostat','Adenuric®'),
    ('Félodipine','Flodil®'),
    ('Fénofibrate','Lipanthyl®'),
    ('Fentanyl','Durogésic® - Abstral®'),
    ('Fenticonazole','Lomexin®'),
    ('Fésotérodine','Toviaz®'),
    ('Féxofénadine','Telfast®'),
    ('Finastéride','Chibro-Proscar®'),
    ('Fingolimod','Gilenya®'),
    ('Flécaïnide','Flécaïne™'),
    ('Fluconazole1','Fluconazole Pfizer®'),
    ('Fluconazole2','Triflucan®'),
    ('Fluoxétine','Prozac®'),
    ('Fluvastatine','Lescol®'),
    ('Fluvoxamine','Floxyfral®'),
    ('Formotérol','Foradil®'),
    ('Fosfomycine','Monuril®'),
    ('Fosinopril','Fozitec®'),
    ('Fosinopril/Hydrochlorothiazide','Foziretic®'),
    ('Frovatriptan','Tigreat®'),
    ('Fulvestrant','Faslodex®'),
    ('Furosémide','Lasilix®'),
    ('Fusidate de sodium','Fucidine®'),
    ('Gabapentine','Neurontin®'),
    ('Galantamine','Reminyl®'),
    ('Ganirelix','Orgalutran®'),
    ('Gefitinib','Iressa®'),
    ('Gestodène Ethinylestradiol (50µg/30µg - 70µg/40µg - 100µg/30µg','Perléane®'),
    ('Gestodene Ethinylestradiol (60 μg/15 µg)','Mélodia - Minesse®'),
    ('Gestodene/Ethinylestradiol (75 µg/20 µg)','Meliane®'),
    ('Gestodène Ethinylestradiol (75 µg/30 µg)','Minulet®'),
    ('Gestodéne/Ethinylestradiol (75 µg/20 µg) et (75 µg/30 µg)','Carlin®'),
    ('Ginkgo','Ginkogink® - Tanakan® - Vitalogink®'),
    ('Glibenclamide','Daonil® - Hémi-Daonil® (Arrêt commercialisation)®'),
    ('Gliclazide','Diamicron®'),
    ('Glimépiride','Amarel®'),
    ('Glycerol/Vaseline/Paraffine','Dexatopia®'),
    ('Glycopyrronium', 'Seebri'),
    ('Héxétidine','Hextril®'),
    ('Hydrochlorothiazide','Esidrex®'),
    ('Hydroxyzine','Atarax®'),
    ('Ibuprofene','Advil®'),
    ('Imatinib','Glivec®'),
    ('Imipénem/Cilastine','Tiénam®'),
    ('Indapamide', 'Fludex®'),
    ('Ipratropium','Atrovent®'),
    ('Irbesartan','Aprovel®'),
    ('Irbesartan/Hydrochlorothiazide','Co-Aprovel®'),
    ('Isotretinoïne','Curacné®'),
    ('Ispaghul (Poudre de tégument de la graine d")','Spagulax®'),
    ('Itraconazole','Sporanox®'),
    ('Ivabradine','Procoralan®'),
    ('Ivermectine','Stromectol®'),
    ('Kétoconazole','Kétoderm®'),
    ('Kétoprofène LP','Bi-Profénid®'),
    ('Kétoprofène','Profénid'),
    ('Kétoprofène gel','Ketum 2,5% (gel)'),
    ('Kétotifène','Zagrapa®'),
    ('Lacosamide','Vimpat®'),
    ('Lactulose','Duphalac®'),
    ('Lamivudine','Epivir® - Zeffix®'),
    ('Lamivudine/Zidovudine','Combivir®'),
    ('Lamotrigine','Lamictal®'),
    ('Lanréotide','Somatuline®'),
    ('Lansoprazole','Lanzor®'),
    ('Lanthane','Fosrenol®'),
    ('Latanoprost','Xalatan®'),
    ('Latanoprost/Timolol','Xalacom®®'),
    ('Léflunomide','Arava®'),
    ('Lercanidipine','Lercan®'),
    ('Létrozole','Femara®'),
    ('Lévétiracétam','Keppra®'),
    ('Lévocétirizine','Xyzall®'),
    ('Lévodopa/Bensérazide','Modopar®'),
    ('Lévodopa/Carbidopa/Entacapone','Stalévo®'),
    ('Levofloxacine','Tavanic®'),
    ('Levonorgestrel 1,5 mg','Lévonorgestrel Biogaran'),
    ('Levonorgestrel/Ethinylestradiol (100 µg / 20µg)','Asterluna Continu - Asterluna- Leeloo Leeloo Continu - Lovavulo-Milevoni (100 µg/20 µg)'),
    ('Lévonorgestrel/Ethinylestradiol (150 µg/30 µg - 200 µg/40 µg)','Adépal®'),
    ('Lévonorgestrel/Ethinylestradiol (150 µg/30 µg)','Minidril®'),
    ('Lévonorgestrel/Ethinylestradiol (50 µg/30 µg - 75 µg/40 µg - 125 µg/30 µg)','Trinordiol®'),
    ('Lévothyroxine','Lévothyrox®'),
    ('Lidocaine','Xylocaine®'),
    ('Lidocaïne/Prilocaïne','Emla® - Emla® patch'),
    ('Lierre grimpant','Herbion® Expectorant Lierre'),
    ('Lisinopril','Zestril®'),
    ('Lisinopril/Hydrochlorothiazide','Zestoretic®'),
    ('Lopéramide','Imodium® '),
    ('Lopinavir/Ritonavir','Kaletra®'),
    ('Loratadine', 'Clarityne®'),
    ('Lorazepam', 'Témesta®'),
    ('Losartan', 'Cozaar®'),
    ('Losartan/Hydrochlorothiazide', 'Hyzaar®'),
    ('Lymécycline', 'Tetralysal®'),
    ('Lormétazépam', 'Noctamide®'),

    ('Macrogol 3350', 'Transipeg®'),
    ('Macrogol 4000', 'Forlax®'),
    ('Magnésium/Vitamine B6', 'Magné B6®'),
    ('Manidipine', 'IperTen®'),
    ('Mélatonine', 'Circadin®'),
    ('Méloxicam', 'Mobic®'),
    ('Mémantine', 'Ebixa®'),
    ('Méropénem', 'Meronem'),
    ('Metformine', 'Glucophage®'),
    ('Méthotrexate', 'Imeth®'),
    ('Méthylphenidate', 'Concerta® - Ritaline®'),
    ('Métoclopramide', 'Primpéran®'),
    ('Métopimazine', 'Vogalène® Lyoc®'),
    ('Métoprolol', 'Lopressor® - Séloken®'),
    ('Métronidazole', 'Flagyl®'),
    ('Midodrine', 'Gutron®'),
    ('Millepertuis (sommité fleurie de)', 'Arkogélules Millepertuis - Prosoft®'),
    ('Minoxidil','	Alostil®'),
    ('Mirtazapine', 'Norset®'),
    ('Modafinil', 'Modiodal®'),
    ('Molsidomine', 'Corvasal®'),
    ('Mométasone', 'Nasonex®'),
    ('Montélukast', 'Singulair®'),
    ('Moxifloxacine', 'Izilox®'),
    ('Moxonidine', 'Physiotens®'),
    ('Mupirocine', 'Mupiderm®'),
    ('Mycophenolate Mofétil', 'Cellcept®'),
    ('Milnacipran', 'Ixel®'),
    ('Mébévérine', 'Duspatalin®'),
    ('Miansérine', 'Athymil®'),
    ('Methocarbamol', 'Lumirelax®'),



    ('Naproxène', 'Apranax®'),
    ('Naratriptan', 'Naramig®'),
    ('Nébivolol', 'Temerit®'),
    ('Nébivolol/Hydrochlorothiazide', 'Temerit-Duo®'),
    ('Néfopam',	'Acupan®'),
    ('Névirapine',	'Viramune®'),
    ('Nicardipine',	'Loxen®'),
    ('Nicorandil',	'Ikorel®'),
    ('Nicotine', 'Nicopass sans sucre menthe fraîcheur Nicorette sans sucre - Nicorettespray® - Nicotinell TTS - NiQuitin sans sucre - Nicopass sans sucre eucalyptus - Nicorette sans sucre - Nicotinell Fruit Exotique - NiQuitin® sans sucre'),
    ('Nomégestrol', 'Lutenyl®'),
    ('Norfloxacine', 'Noroxine®'),
    ('Norgestimate/Ethinylestradiol (0,180 mg/0,035 mg-0,215 mg/ 0.035 mg-0,250 mg/0,035 mg)', 'Triafémi®'),
    ('Norgestimate/Ethinylestradiol (250 µg/35 µg)', 'Naravela®'),
    ('Nitrendipine', 'Nidrel®'),


    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),
    # ('Loratadine', ''),












]

for mol, brand in medicaments:
    c.execute("SELECT id FROM medecine WHERE molecule = ?", (mol,))
    if (c.fetchone() is None):
        resSearch = ''.join((c for c in unicodedata.normalize('NFD', mol) if unicodedata.category(c) != 'Mn'))
        molSearch = resSearch.lower()
        c.execute("INSERT INTO medecine (molecule, brand, moleculeSearch) VALUES (?, ?, ?)", (mol, brand, molSearch))

#ecrit definitivement sur le disque
conn.commit()

#repose le stylo et ferme le classeur 
conn.close()

print("Données insérées !")
