import sqlite3

#ouvre le classeur
conn = sqlite3.connect('./instance/pharmaapp.sqlite')

#sert d'intermediaire à la db pour insérer, supprimer etc, exec des commandes à la db
c = conn.cursor()

medicaments = [
    ('Atorvastatine', 'TAHOR'),
    ('Fluvastatine', 'LESCOL'),
    ('Pravastatine', 'ELISOR'),
    ('Rosuvastatine', 'CRESTOR'),
    ('Simvastatine', 'ZOCOR'),
    ('Atorvastatine/Amlodipine', 'CADUET'),
    ('Atorvastatine/Ézétimibe', 'LIPTRUZET'),
    ('Pravastatine/Acide acétylsalicylique','PRAVADUAL'),
    ('Simvastatine/Ézétimibe', 'INEGY'),
    ('Bézafibrate', 'BEFIZAL'),
    ('Ciprofibrate', 'LIPANOR®'),
    ('Fénofibrate', 'LIPANTHYL®'),
    ('Gemfibrozil','LIPUR®'),
    ('Ezétimibe', 'EZETROL®'),

    ('Acarbose', 'GLUCOR®'),
    ('Miglitol', 'DIASTABOL®'),
    ('Glibenclamide', 'DAONIL®'),
    ('Gliclazide', 'DIAMICRON®'),
    ('Glimépiride', 'AMAREL®'),
    ('Glipizide', 'GLIBENESE®/MINIDIAB®'),
    ('Metformine', 'GLUCOPHAGE®'),
    ('Répaglinide', 'NOVONORM®'),
    ('Saxagliptine', 'ONGLYZA®'),
    ('Sitagliptine', 'JANUVIA®'),
    ('Vildagliptine', 'GALVUS®'),
    ('Metformine/Saxagliptine', 'KOMBOGLYZE®'),
    ('Metformine/Sitagliptine', 'JANUMET®'),
    ('Metformine/Vildagliptine','EUCREAS®'),

    ('Citalopram', 'SEROPRAM®'),
    ('Escitalopram', 'SEROPLEX®'),
    ('Fluoxétine', 'PROZAC®'),
    ('Fluvoxamine', 'FLOXYFRAL®'),
    ('Paroxétine', 'DEROXAT®'),
    ('Sertraline', 'ZOLOFT®'),
    ('Duloxétine', 'CYMBALTA®'),
    ('Milnacipran', 'IXEL®'),
    ('Venlafaxine', 'EFFEXOR®'),
    ('Amitriptyline', 'LAROXYL®'),
    ('Amoxapine', 'DEFANYL®'),
    ('Clomipramine', 'ANAFRANIL®'),
    ('Dosulépine', 'PROTHIADEN®'),
    ('Doxépine', 'QUITAXON®'),
    ('Imipramine', 'TOFRANIL®'),
    ('Maprotiline', 'LUDIOMIL®'),
    ('Trimipramine', 'SURMONTIL®'),
    ('Iproniazide', 'MARSILID®'),
    ('Moclobémide', 'MOCLAMINE®'),
    ('Agomélatine', 'VALDOXAN®'),
    ('Miansérine', 'ATHYMIL®**'),
    ('Mirtazapine', 'NORSET®'),
    ('Tianeptine', 'STABLON®'),
    
    ('Eplérénone', 'INSPRA®'),
    ('Furosémide', 'LASILIX®'),
    ('Hydrochlorothiazide', 'ESIDREX®'),
    ('Amiloride/Hydrochlorothiazide', 'MODURETIC®'),
    ('Indapamide', 'FLUDEX®'),
    ('Spironolactone', 'ALDACTONE®'),
    ('Spironolactone/Altizide', 'ALDACTAZINE®'),
    ('Amlodipine', 'AMLOR®'),
    ('Diltiazem', 'MONOTILDIEM®'),
    ('Félodipine', 'FLODIL®'),
    ('Isradipine', 'ICAZ®'),
    ('Lercanidipine', 'LERCAN®'),
    ('Manidipine', 'IPERTEN®'),
    ('Nicardipine', 'LOXEN®'),
    ('Nifédipine', 'ADALATE®'),
    ('Vérapamil', 'ISOPTINE®'),
    ('Captopril', 'LOPRIL®'),
    ('Enalapril', 'RENITEC®'),
    ('Lisinopril', 'ZESTRIL®'),
    ('Périndopril', 'COVERSYL®'),
    ('Ramipril', 'TRIATEC®'),
    ('Trandolapril', 'ODRIK®'),

    ('Candésartan', 'ATACAND®'),
    ('Irbésartan', 'APROVEL®'),
    ('Losartan', 'COZAAR®'),
    ('Telmisartan', 'MICARDIS®'),
    ('Valsartan', 'TAREG®'),
    ('Acébutolol', 'SECTRAL®'),
    ('Aténolol', 'TENORMINE®'),
    ('Bétaxolol', 'KERLONE®'),
    ('Bisoprolol 10MG', 'DETENSIEL®'),
    ('Bisoprolol < 10MG', 'CARDENTIEL'),
    ('Céliprolol', 'CELECTOL®'),
    ('Labétalol', 'TRANDATE®'),
    ('Métoprolol', 'SELOKEN®'),
    ('Nébivolol', 'TEMERIT®'),
    ('Propranolol', 'AVLOCARDYL®'),
    ('Bisoprolol/Hydrochlorothiazide', 'LODOZ®'),
    ('Métoprolol/Félodipine', 'LOGIMAX®'),
    ('Nébivolol/Hydrochlorothiazide', 'TEMERITDUO®'),
    ('Enalapril/Hydrochlorothiazide', 'CO-RENITEC®'),
    ('Enalapril/Lercanidipine', 'LERCAPRESS®'),
    ('Lisinopril/Hydrochlorothiazide', 'ZESTORETIC®'),
    ('Périndopril/Amlodipine', 'COVERAM®'),
    ('Périndopril/Indapamide', 'PRETERAX®'),
    ('Ramipril/Hydrochlorothiazide', 'COTRIATEC®'),
    ('Trandolapril/Vérapamil', 'TARKA®'),
    ('Candésartan/Hydrochlorothiazide', 'HYTACAND®'),
    ('Irbésartan/Hydrochlorothiazide', 'COAPROVEL®'),
    ('Losartan/Hydrochlorothiazide', 'HYZAAR®'),
    ('Telmisartan/Hydrochlorothiazide', 'MICARDISPLUS®'),
    ('Amlodipine/Valsartan', 'EXFORGE®'),
    ('Valsartan/Hydrochlorothiazide', 'COTAREG®'),

    ('Amoxicilline', 'CLAMOXYL®'),
    ('Amoxicilline/Acide clavulanique', 'AUGMENTIN®'),
    ('Cloxacilline', 'ORBENINE®'),
    ('Oxacilline', 'BRISTOPEN®'),
    ('Phénoxyméthylpénicilline', 'ORACILLINE®'),
    ('Pipéracilline/Tazobactam', 'TAZOCILLINE®'),
    ('Céfaclor', 'ALFATIL®'),
    ('Céfépime', 'AXEPIM®'),
    ('Céfixime', 'OROKEN®'),
    ('Cefpodoxime', 'ORELOX®'),
    ('Ceftazidime', 'FORTUM®'),
    ('Ceftriaxone', 'ROCEPHINE®'),
    ('Céfuroxime', 'ZINNAT®'),
    ('Azithromycine', 'ZITHROMAX®'),
    ('Clarithromycine', 'ZECLAR®'),
    ('Clindamycine', 'DALACINE®'),
    ('Josamycine', 'JOSACINE®'),
    ('Roxithromycine' ,'RULID®'),
    ('Spiramycine', 'ROVAMYCINE®'),
    ('Spiramycine/métronidazole', 'BIRODOGYL®'),
    ('Ciprofloxacine', 'CIFLOX®'),
    ('Lévofloxacine' ,'TAVANIC®'),
    ('Moxifloxacine', 'IZILOX®'),
    ('Norfloxacine' ,'NOROXINE®'),
    ('Ofloxacine' ,'OFLOCET®'),
    ('Doxycycline' ,'VIBRAMYCINE®'),
    ('Lymécycline' ,'TETRALYSAL®'),
    ('Gentamicine' ,'GENTALLINE®'),
    ('Tobramycine' ,'NEBCINE®'),
    ('Acide fusidique' ,'FUCIDINE®'),
    ('Aztréonam' ,'AZACTAM®'),
    ('Colistine' ,'COLIMYCINE®'),
    ('Fosfomycine' ,'MONURIL®'),
    ('Imipénème/cilastatine' ,'TIENAM®'),
    ('Nitrofurantoïne' ,'FURADANTINE®'),
    ('Pristinamycine' ,'PYOSTACINE®'),
    ('Sulfaméthoxazole/triméthoprim' ,'BACTRIM®'),

    ('Clopidogrel', 'PLAVIX ®'),
    ('Ticlopidine', 'TICLID ®'),
    ('Anastrozole', 'ARIMIDEX®'),
    ('Bicalutamide', 'CASODEX®'),
    ('Capécitabine', 'XELODA®'),
    ('Cyprotérone', 'ANDROCUR®'),
    ('Exémestane' ,'AROMASINE®'),
    ('Flutamide', 'EULEXINE®*'),
    ('Létrozole' ,'FEMARA®'),
    ('Tamoxifène', 'NOLVADEX®'),
    ('Acide zolédronique' ,'ZOMETA®'),
    ('Ondansétron', 'ZOPHREN®'),
    ('Aciclovir', 'ZOVIRAX®**'),
    ('Efavirenz', 'SUSTIVA®'),
    ('Lamivudine', 'EPIVIR®**'),
    ('Lamivudine/Zidovudine', 'COMBIVIR®'),
    ('Névirapine', 'VIRAMUNE®'),
    ('Ribavirine' ,'REBETOL®** (suspension ou sol buvable)/COPEGUS®'),
    ('Valaciclovir', 'ZELITREX®'),
    ('Fluconazole', 'TRIFLUCAN®'),
    ('Itraconazole', 'SPORANOX®**'),
    ('Terbinafine', 'LAMISIL®'),
    ('Carbamazépine', 'TEGRETOL®**'),
    ('Gabapentine', 'NEURONTIN®'),
    ('Lamotrigine', 'LAMICTAL®'),
    ('Lévétiracétam', 'KEPPRA®'),
    ('Oxcarbazépine', 'TRILEPTAL®**'),
    ('Prégabaline', 'LYRICA®'),
    ('Topiramate', 'EPITOMAX®'),
    ('Valproate de sodium', 'DEPAKINE®/DEPAKINE CHRONO®***'),
    ('Bromocriptine', 'PARLODEL®'),
    ('Entacapone', 'COMTAN®'),
    ('Lévodopa/Bensérazide', 'MODOPAR®'),
    ('Lévodopa/Carbidopa', 'SINEMET®'),
    ('Lévodopa/Carbidopa/Entacapone', 'STALEVO®'),
    ('Pramipexol', 'SIFROL®'),
    ('Ropinirole', 'REQUIP®'),
    ('Sélégiline' ,'DEPRENYL®'),
    ('Amisulpride' ,'SOLIAN®'),
    ('Aripiprazole', 'ABILIFY®****'),
    ('Clozapine', 'LEPONEX®'),
    ('Olanzapine', 'ZYPREXA®'),
    ('Quétiapine',	'XEROQUEL®'),
    ('Rispéridone', 'RISPERDAL®'),
    ('Sulpiride', 'DOGMATIL®'),
    ('Tiapride', 'TIAPRIDAL®******'),
    ('Azathioprine', 'IMUREL®'),
    ('Mycophénolate mofétil', 'CELLCEPT®*******'),
    ('Esoméprazole', 'INEXIUM®'),
    ('Lansoprazole', 'LANZOR®'),
    ('Oméprazole', 'MOPRAL®'),
    ('Pantoprazole', 'INIPOMP®'),
    ('Rabéprazole', 'PARIET®'),


     
]

for mol, brand in medicaments:
    c.execute("SELECT id FROM medecine WHERE molecule = ?", (mol,))
    if (c.fetchone() is None):
        c.execute("INSERT INTO medecine (molecule, brand) VALUES (?, ?)", (mol, brand))

#ecrit definitivement sur le disque
conn.commit()

#repose le stylo et ferme le classeur 
conn.close()

print("Données insérées !")
